In [1]:
import numpy as np
import matplotlib
matplotlib.use('nbagg')
import matplotlib.pyplot as plt 

In [2]:
N = 10
D = 3

In [3]:
X = np.zeros((N, D))
X[:, 0] = 1  #bias column
X[:5, 1] = 1
X[-5:, 2] = 1
X

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.]])

In [4]:
Y = np.array([0] * 5 + [1] * 5)
Y

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

here regular fit wont work since X transpose X is singular matrix

In [5]:
costs = []
w = np.random.randn(D) / np.sqrt(D)

learning_rate = 0.001


for t in range(1000) :
    yhat = X.dot(w)
    delta = yhat - Y
    w = w - learning_rate * X.T.dot(delta)
    d2 = Y - Y.mean()
    mse =  delta.dot(delta) / d2.dot(d2)
    costs.append(mse)

plt.plot(costs, label = 'costs')
# plt.plot(yhat, label = 'prediction')
# plt.plot(Y, label = 'targets')
# plt.legend()
plt.show()
w

<IPython.core.display.Javascript object>

array([ 0.71902727, -0.71640779,  0.27835337])