In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
def happyness_model () :
    weather = yield tfp.distributions.JointDistributionCoroutine.Root(
        tfp.distributions.Bernoulli(probs=0.3, name = 'weather')
    )
    
    weather_to_happyness = tf.constant([0.6, 0.9])
    happyness = yield tfp.distributions.Bernoulli(
        probs= weather_to_happyness[weather], name = 'happyness'
    )

In [3]:
model_joint = tfp.distributions.JointDistributionCoroutineAutoBatched(happyness_model)
model_joint

<tfp.distributions.JointDistributionCoroutineAutoBatched 'JointDistributionCoroutineAutoBatched' batch_shape=[] event_shape=StructTuple(
  weather=[],
  happyness=[]
) dtype=StructTuple(
  weather=int32,
  happyness=int32
)>

In [7]:
model_joint.sample(10)

StructTuple(
  weather=<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 1, 1, 0, 1, 0])>,
  happyness=<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 0, 0, 0, 1, 1, 1, 0, 1, 1])>
)

In [8]:
model_joint.prob([1, 1]) #good weather, good mood

<tf.Tensor: shape=(), dtype=float32, numpy=0.27>